### ISSUE TITLE
Add cross-browser support.

### ISSUE THREAD

**Issue by ethernian** [dapplets/dapplet-extension#2]
### Specification:
The current extension is a chrome one. We need to create support for safari and later for other browsers. 

### DesignChoices: 
- Usage of generic cross-browser abstraction layers is discouraged because we are using only the small subset of the API. 

### ToDo:
- [x] Find articles and examples for cross-browser extensions.
- [ ] extract browser specifica from current extension implementation
- [ ] _PUT HERE: more  implementation steps_

**Comment by ethernian** [comment]
**Result:** Postponed because safari needs swift & c programming now. It is not a trivial task and not fit to MVP. 

### [card-20492751](https://github.com/orgs/dapplets/projects/1#card-20492751)
From: [cross-browser](https://github.com/orgs/dapplets/projects/1#card-20492751)
#### README:
- [x] [Grammarly: how to build extension](https://tech.grammarly.com/blog/building-browser-extensions-at-scale)
- [x] Cross-browser extensions [EN](http://frontendbabel.info/articles/developing-cross-browser-extensions/) [RU](https://habr.com/ru/company/likeastore/blog/227881/)
- [x] [Octotree: cross-browser extension](https://github.com/ovity/octotree)
- [x] [Creating Safari App Extensions and porting old Safari extensions](https://blog.yimingliu.com/2018/11/14/notes-on-porting-a-safari-extension-to-a-safari-app-extension/)
- [x] [SafariExtentions by AppleDev](https://developer.apple.com/documentation/safariextensions)

### [card-20492751](https://github.com/orgs/dapplets/projects/1#card-20492751)
BreakDown: [ext#2: cross-browser support](https://github.com/orgs/dapplets/projects/1#card-20492945)

- [x] [evaluate article and examples](#card-20506986)
- [ ] extract browser specific
- [ ] define extension API
- [ ] implement chrome
- [ ] implement safari

**Comment by Gromazek** [comment]
test 1

**Comment by Gromazek** [comment]
test6
